language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run
before_script:
  - docker --version # Print the version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed nmcuong166/udagram-api-feed:latest
  - docker tag udagram-api-user nmcuong166/udagram-api-user:latest
  - docker tag udagram-frontend nmcuong166/udagram-frontend:latest
  - docker tag reverseproxy nmcuong166/udagram-reverseproxy:latest

after_success:
  - docker login -u nmcuong166 -p Manhcuong1992
  - docker push nmcuong166/udagram-api-feed:latest
  - docker push nmcuong166/udagram-api-user:latest
  - docker push nmcuong166/udagram-frontend:latest
  - docker push nmcuong166/udagram-reverseproxy:latest