name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: nmcuong166
        DOCKER_PASSWORD: Manhcuong1992
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-reverseproxy
          file: ./udagram-reverseproxy/Dockerfile
          push: true
          tags: nmcuong166/udagram-reverseproxy:latest
          cache-from: type=registry,ref=nmcuong166/udagram-reverseproxy:buildcache
          cache-to: type=registry,ref=nmcuong166/udagram-reverseproxy:buildcache,mode=max
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-frontend
          file: ./udagram-frontend/Dockerfile
          push: true
          tags: nmcuong166/udagram-frontend:v1
          cache-from: type=registry,ref=nmcuong166/udagram-frontend:buildcache
          cache-to: type=registry,ref=nmcuong166/udagram-frontend:buildcache,mode=max
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-feed
          file: ./udagram-api-feed/Dockerfile
          push: true
          tags: nmcuong166/udagram-api-feed:latest
          cache-from: type=registry,ref=nmcuong166/udagram-api-feed:buildcache
          cache-to: type=registry,ref=nmcuong166/udagram-api-feed:buildcache,mode=max
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-user
          file: ./udagram-api-user/Dockerfile
          push: true
          tags: nmcuong166/udagram-api-user:latest
          cache-from: type=registry,ref=nmcuong166/udagram-api-user:buildcache
          cache-to: type=registry,ref=nmcuong166/udagram-api-user:buildcache,mode=max